-- Seed 001: published levels for the Arrow Untangle catalog.
-- GENERATED by scripts/generate-level-seed.ts — do not edit by hand; re-run the script.
-- Each level is a set of bendable snake-arrows; every level is a verified DAG (solvable).
-- Arrows are stored as JSONB: { id, color, path:[{row,col}, ... tail->head], direction }.

-- Level 1: First Knot (EASY, 2 arrows, 5 attempts)
INSERT INTO levels (id, name, description, difficulty, status, version, arrows, attempts, time_limit_seconds, created_at, updated_at)
VALUES (
  '550e8400-e29b-41d4-a716-446655440010',
  'First Knot',
  'Your first untangle. Tap arrows so each flies off a clear path.',
  'EASY',
  'PUBLISHED',
  1,
  '[{"id":"a","color":"blue","path":[{"row":0,"col":0},{"row":0,"col":1},{"row":0,"col":2},{"row":0,"col":3},{"row":0,"col":4}],"direction":"RIGHT"},{"id":"b","color":"green","path":[{"row":3,"col":1},{"row":3,"col":2},{"row":2,"col":2},{"row":1,"col":2}],"direction":"UP"}]'::jsonb,
  5,
  NULL,
  NOW(),
  NOW()
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  difficulty = EXCLUDED.difficulty,
  status = EXCLUDED.status,
  version = EXCLUDED.version,
  arrows = EXCLUDED.arrows,
  attempts = EXCLUDED.attempts,
  time_limit_seconds = EXCLUDED.time_limit_seconds,
  updated_at = EXCLUDED.updated_at;

-- Level 2: Warm-Up (EASY, 3 arrows, 5 attempts)
INSERT INTO levels (id, name, description, difficulty, status, version, arrows, attempts, time_limit_seconds, created_at, updated_at)
VALUES (
  '550e8400-e29b-41d4-a716-446655440011',
  'Warm-Up',
  'Three arrows, one right order. Clear the board.',
  'EASY',
  'PUBLISHED',
  1,
  '[{"id":"a","color":"blue","path":[{"row":0,"col":0},{"row":0,"col":1},{"row":0,"col":2},{"row":0,"col":3},{"row":0,"col":4}],"direction":"RIGHT"},{"id":"b","color":"green","path":[{"row":3,"col":1},{"row":3,"col":2},{"row":2,"col":2},{"row":1,"col":2}],"direction":"UP"},{"id":"c","color":"yellow","path":[{"row":5,"col":5},{"row":4,"col":5},{"row":3,"col":5},{"row":3,"col":6},{"row":3,"col":7}],"direction":"RIGHT"}]'::jsonb,
  5,
  NULL,
  NOW(),
  NOW()
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  difficulty = EXCLUDED.difficulty,
  status = EXCLUDED.status,
  version = EXCLUDED.version,
  arrows = EXCLUDED.arrows,
  attempts = EXCLUDED.attempts,
  time_limit_seconds = EXCLUDED.time_limit_seconds,
  updated_at = EXCLUDED.updated_at;

-- Level 3: Cross (EASY, 3 arrows, 5 attempts)
INSERT INTO levels (id, name, description, difficulty, status, version, arrows, attempts, time_limit_seconds, created_at, updated_at)
VALUES (
  '550e8400-e29b-41d4-a716-446655440012',
  'Cross',
  'Bodies start to bend and cross. Free the blocked ones.',
  'EASY',
  'PUBLISHED',
  1,
  '[{"id":"a","color":"blue","path":[{"row":0,"col":0},{"row":0,"col":1},{"row":0,"col":2},{"row":0,"col":3},{"row":0,"col":4}],"direction":"RIGHT"},{"id":"b","color":"green","path":[{"row":3,"col":1},{"row":3,"col":2},{"row":2,"col":2},{"row":1,"col":2}],"direction":"UP"},{"id":"c","color":"yellow","path":[{"row":5,"col":5},{"row":4,"col":5},{"row":3,"col":5},{"row":3,"col":6},{"row":3,"col":7}],"direction":"RIGHT"}]'::jsonb,
  5,
  NULL,
  NOW(),
  NOW()
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  difficulty = EXCLUDED.difficulty,
  status = EXCLUDED.status,
  version = EXCLUDED.version,
  arrows = EXCLUDED.arrows,
  attempts = EXCLUDED.attempts,
  time_limit_seconds = EXCLUDED.time_limit_seconds,
  updated_at = EXCLUDED.updated_at;

-- Level 4: Tangle (EASY, 4 arrows, 5 attempts)
INSERT INTO levels (id, name, description, difficulty, status, version, arrows, attempts, time_limit_seconds, created_at, updated_at)
VALUES (
  '550e8400-e29b-41d4-a716-446655440013',
  'Tangle',
  'Four snakes weave together. Find what''s free now.',
  'EASY',
  'PUBLISHED',
  1,
  '[{"id":"a","color":"blue","path":[{"row":0,"col":0},{"row":0,"col":1},{"row":0,"col":2},{"row":0,"col":3},{"row":0,"col":4}],"direction":"RIGHT"},{"id":"b","color":"green","path":[{"row":3,"col":1},{"row":3,"col":2},{"row":2,"col":2},{"row":1,"col":2}],"direction":"UP"},{"id":"c","color":"yellow","path":[{"row":5,"col":5},{"row":4,"col":5},{"row":3,"col":5},{"row":3,"col":6},{"row":3,"col":7}],"direction":"RIGHT"},{"id":"d","color":"pink","path":[{"row":2,"col":1},{"row":2,"col":2},{"row":1,"col":2}],"direction":"UP"}]'::jsonb,
  5,
  NULL,
  NOW(),
  NOW()
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  difficulty = EXCLUDED.difficulty,
  status = EXCLUDED.status,
  version = EXCLUDED.version,
  arrows = EXCLUDED.arrows,
  attempts = EXCLUDED.attempts,
  time_limit_seconds = EXCLUDED.time_limit_seconds,
  updated_at = EXCLUDED.updated_at;

-- Level 5: Weave (EASY, 4 arrows, 5 attempts)
INSERT INTO levels (id, name, description, difficulty, status, version, arrows, attempts, time_limit_seconds, created_at, updated_at)
VALUES (
  '550e8400-e29b-41d4-a716-446655440014',
  'Weave',
  'Look before you tap: pick the order that unwinds the knot.',
  'EASY',
  'PUBLISHED',
  1,
  '[{"id":"a","color":"blue","path":[{"row":0,"col":0},{"row":0,"col":1},{"row":0,"col":2},{"row":0,"col":3},{"row":0,"col":4}],"direction":"RIGHT"},{"id":"b","color":"green","path":[{"row":3,"col":1},{"row":3,"col":2},{"row":2,"col":2},{"row":1,"col":2}],"direction":"UP"},{"id":"c","color":"yellow","path":[{"row":5,"col":5},{"row":4,"col":5},{"row":3,"col":5},{"row":3,"col":6},{"row":3,"col":7}],"direction":"RIGHT"},{"id":"d","color":"pink","path":[{"row":2,"col":1},{"row":2,"col":2},{"row":1,"col":2}],"direction":"UP"}]'::jsonb,
  5,
  NULL,
  NOW(),
  NOW()
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  difficulty = EXCLUDED.difficulty,
  status = EXCLUDED.status,
  version = EXCLUDED.version,
  arrows = EXCLUDED.arrows,
  attempts = EXCLUDED.attempts,
  time_limit_seconds = EXCLUDED.time_limit_seconds,
  updated_at = EXCLUDED.updated_at;

-- Level 6: Stack (MEDIUM, 5 arrows, 5 attempts)
INSERT INTO levels (id, name, description, difficulty, status, version, arrows, attempts, time_limit_seconds, created_at, updated_at)
VALUES (
  '550e8400-e29b-41d4-a716-446655440015',
  'Stack',
  'Five arrows stacked into a tighter knot.',
  'MEDIUM',
  'PUBLISHED',
  1,
  '[{"id":"a","color":"blue","path":[{"row":0,"col":0},{"row":0,"col":1},{"row":0,"col":2},{"row":0,"col":3},{"row":0,"col":4},{"row":0,"col":5}],"direction":"RIGHT"},{"id":"b","color":"green","path":[{"row":3,"col":1},{"row":3,"col":2},{"row":2,"col":2},{"row":1,"col":2}],"direction":"UP"},{"id":"c","color":"yellow","path":[{"row":5,"col":6},{"row":4,"col":6},{"row":3,"col":6},{"row":3,"col":7},{"row":3,"col":8}],"direction":"RIGHT"},{"id":"d","color":"pink","path":[{"row":2,"col":0},{"row":2,"col":1},{"row":1,"col":1}],"direction":"UP"},{"id":"e","color":"cyan","path":[{"row":2,"col":5},{"row":1,"col":5},{"row":1,"col":6},{"row":1,"col":7}],"direction":"RIGHT"}]'::jsonb,
  5,
  NULL,
  NOW(),
  NOW()
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  difficulty = EXCLUDED.difficulty,
  status = EXCLUDED.status,
  version = EXCLUDED.version,
  arrows = EXCLUDED.arrows,
  attempts = EXCLUDED.attempts,
  time_limit_seconds = EXCLUDED.time_limit_seconds,
  updated_at = EXCLUDED.updated_at;

-- Level 7: Rush (MEDIUM, 5 arrows, 75s, 5 attempts)
INSERT INTO levels (id, name, description, difficulty, status, version, arrows, attempts, time_limit_seconds, created_at, updated_at)
VALUES (
  '550e8400-e29b-41d4-a716-446655440016',
  'Rush',
  'Same idea, against the clock. Be quick and clean.',
  'MEDIUM',
  'PUBLISHED',
  1,
  '[{"id":"a","color":"blue","path":[{"row":0,"col":0},{"row":0,"col":1},{"row":0,"col":2},{"row":0,"col":3},{"row":0,"col":4},{"row":0,"col":5}],"direction":"RIGHT"},{"id":"b","color":"green","path":[{"row":3,"col":1},{"row":3,"col":2},{"row":2,"col":2},{"row":1,"col":2}],"direction":"UP"},{"id":"c","color":"yellow","path":[{"row":5,"col":6},{"row":4,"col":6},{"row":3,"col":6},{"row":3,"col":7},{"row":3,"col":8}],"direction":"RIGHT"},{"id":"d","color":"pink","path":[{"row":2,"col":0},{"row":2,"col":1},{"row":1,"col":1}],"direction":"UP"},{"id":"e","color":"cyan","path":[{"row":2,"col":5},{"row":1,"col":5},{"row":1,"col":6},{"row":1,"col":7}],"direction":"RIGHT"}]'::jsonb,
  5,
  75,
  NOW(),
  NOW()
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  difficulty = EXCLUDED.difficulty,
  status = EXCLUDED.status,
  version = EXCLUDED.version,
  arrows = EXCLUDED.arrows,
  attempts = EXCLUDED.attempts,
  time_limit_seconds = EXCLUDED.time_limit_seconds,
  updated_at = EXCLUDED.updated_at;

-- Level 8: Lattice (MEDIUM, 6 arrows, 5 attempts)
INSERT INTO levels (id, name, description, difficulty, status, version, arrows, attempts, time_limit_seconds, created_at, updated_at)
VALUES (
  '550e8400-e29b-41d4-a716-446655440017',
  'Lattice',
  'Six snakes overlap into a lattice. Read the rays.',
  'MEDIUM',
  'PUBLISHED',
  1,
  '[{"id":"a","color":"blue","path":[{"row":0,"col":0},{"row":0,"col":1},{"row":0,"col":2},{"row":0,"col":3},{"row":0,"col":4},{"row":0,"col":5}],"direction":"RIGHT"},{"id":"b","color":"green","path":[{"row":3,"col":1},{"row":3,"col":2},{"row":2,"col":2},{"row":1,"col":2}],"direction":"UP"},{"id":"c","color":"yellow","path":[{"row":5,"col":6},{"row":4,"col":6},{"row":3,"col":6},{"row":3,"col":7},{"row":3,"col":8}],"direction":"RIGHT"},{"id":"d","color":"pink","path":[{"row":2,"col":0},{"row":2,"col":1},{"row":1,"col":1}],"direction":"UP"},{"id":"e","color":"cyan","path":[{"row":2,"col":5},{"row":1,"col":5},{"row":1,"col":6},{"row":1,"col":7}],"direction":"RIGHT"},{"id":"f","color":"purple","path":[{"row":3,"col":-2},{"row":3,"col":-1},{"row":3,"col":0},{"row":2,"col":0},{"row":1,"col":0}],"direction":"UP"}]'::jsonb,
  5,
  NULL,
  NOW(),
  NOW()
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  difficulty = EXCLUDED.difficulty,
  status = EXCLUDED.status,
  version = EXCLUDED.version,
  arrows = EXCLUDED.arrows,
  attempts = EXCLUDED.attempts,
  time_limit_seconds = EXCLUDED.time_limit_seconds,
  updated_at = EXCLUDED.updated_at;

-- Level 9: Pressure (MEDIUM, 6 arrows, 70s, 5 attempts)
INSERT INTO levels (id, name, description, difficulty, status, version, arrows, attempts, time_limit_seconds, created_at, updated_at)
VALUES (
  '550e8400-e29b-41d4-a716-446655440018',
  'Pressure',
  'Six arrows, a timer, and longer bodies.',
  'MEDIUM',
  'PUBLISHED',
  1,
  '[{"id":"a","color":"blue","path":[{"row":0,"col":0},{"row":0,"col":1},{"row":0,"col":2},{"row":0,"col":3},{"row":0,"col":4},{"row":0,"col":5}],"direction":"RIGHT"},{"id":"b","color":"green","path":[{"row":3,"col":1},{"row":3,"col":2},{"row":2,"col":2},{"row":1,"col":2}],"direction":"UP"},{"id":"c","color":"yellow","path":[{"row":5,"col":6},{"row":4,"col":6},{"row":3,"col":6},{"row":3,"col":7},{"row":3,"col":8}],"direction":"RIGHT"},{"id":"d","color":"pink","path":[{"row":2,"col":0},{"row":2,"col":1},{"row":1,"col":1}],"direction":"UP"},{"id":"e","color":"cyan","path":[{"row":2,"col":5},{"row":1,"col":5},{"row":1,"col":6},{"row":1,"col":7}],"direction":"RIGHT"},{"id":"f","color":"purple","path":[{"row":3,"col":-2},{"row":3,"col":-1},{"row":3,"col":0},{"row":2,"col":0},{"row":1,"col":0}],"direction":"UP"}]'::jsonb,
  5,
  70,
  NOW(),
  NOW()
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  difficulty = EXCLUDED.difficulty,
  status = EXCLUDED.status,
  version = EXCLUDED.version,
  arrows = EXCLUDED.arrows,
  attempts = EXCLUDED.attempts,
  time_limit_seconds = EXCLUDED.time_limit_seconds,
  updated_at = EXCLUDED.updated_at;

-- Level 10: Medium Finale (MEDIUM, 7 arrows, 65s, 5 attempts)
INSERT INTO levels (id, name, description, difficulty, status, version, arrows, attempts, time_limit_seconds, created_at, updated_at)
VALUES (
  '550e8400-e29b-41d4-a716-446655440019',
  'Medium Finale',
  'Seven arrows close out the medium tier.',
  'MEDIUM',
  'PUBLISHED',
  1,
  '[{"id":"a","color":"blue","path":[{"row":0,"col":0},{"row":0,"col":1},{"row":0,"col":2},{"row":0,"col":3},{"row":0,"col":4},{"row":0,"col":5},{"row":0,"col":6}],"direction":"RIGHT"},{"id":"b","color":"green","path":[{"row":3,"col":1},{"row":3,"col":2},{"row":2,"col":2},{"row":1,"col":2}],"direction":"UP"},{"id":"c","color":"yellow","path":[{"row":5,"col":7},{"row":4,"col":7},{"row":3,"col":7},{"row":3,"col":8},{"row":3,"col":9}],"direction":"RIGHT"},{"id":"d","color":"pink","path":[{"row":2,"col":-1},{"row":2,"col":0},{"row":1,"col":0}],"direction":"UP"},{"id":"e","color":"cyan","path":[{"row":2,"col":6},{"row":1,"col":6},{"row":1,"col":7},{"row":1,"col":8}],"direction":"RIGHT"},{"id":"f","color":"purple","path":[{"row":3,"col":2},{"row":3,"col":3},{"row":3,"col":4},{"row":2,"col":4},{"row":1,"col":4}],"direction":"UP"},{"id":"g","color":"crimson","path":[{"row":4,"col":6},{"row":3,"col":6},{"row":3,"col":7}],"direction":"RIGHT"}]'::jsonb,
  5,
  65,
  NOW(),
  NOW()
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  difficulty = EXCLUDED.difficulty,
  status = EXCLUDED.status,
  version = EXCLUDED.version,
  arrows = EXCLUDED.arrows,
  attempts = EXCLUDED.attempts,
  time_limit_seconds = EXCLUDED.time_limit_seconds,
  updated_at = EXCLUDED.updated_at;

-- Level 11: Hard Knot (HARD, 7 arrows, 4 attempts)
INSERT INTO levels (id, name, description, difficulty, status, version, arrows, attempts, time_limit_seconds, created_at, updated_at)
VALUES (
  '550e8400-e29b-41d4-a716-446655440020',
  'Hard Knot',
  'Hard tier: fewer attempts, denser crossings.',
  'HARD',
  'PUBLISHED',
  1,
  '[{"id":"a","color":"blue","path":[{"row":0,"col":0},{"row":0,"col":1},{"row":0,"col":2},{"row":0,"col":3},{"row":0,"col":4},{"row":0,"col":5},{"row":0,"col":6}],"direction":"RIGHT"},{"id":"b","color":"green","path":[{"row":3,"col":1},{"row":3,"col":2},{"row":2,"col":2},{"row":1,"col":2}],"direction":"UP"},{"id":"c","color":"yellow","path":[{"row":5,"col":7},{"row":4,"col":7},{"row":3,"col":7},{"row":3,"col":8},{"row":3,"col":9}],"direction":"RIGHT"},{"id":"d","color":"pink","path":[{"row":2,"col":-1},{"row":2,"col":0},{"row":1,"col":0}],"direction":"UP"},{"id":"e","color":"cyan","path":[{"row":2,"col":6},{"row":1,"col":6},{"row":1,"col":7},{"row":1,"col":8}],"direction":"RIGHT"},{"id":"f","color":"purple","path":[{"row":3,"col":2},{"row":3,"col":3},{"row":3,"col":4},{"row":2,"col":4},{"row":1,"col":4}],"direction":"UP"},{"id":"g","color":"crimson","path":[{"row":4,"col":6},{"row":3,"col":6},{"row":3,"col":7}],"direction":"RIGHT"}]'::jsonb,
  4,
  NULL,
  NOW(),
  NOW()
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  difficulty = EXCLUDED.difficulty,
  status = EXCLUDED.status,
  version = EXCLUDED.version,
  arrows = EXCLUDED.arrows,
  attempts = EXCLUDED.attempts,
  time_limit_seconds = EXCLUDED.time_limit_seconds,
  updated_at = EXCLUDED.updated_at;

-- Level 12: Hard Timer (HARD, 8 arrows, 70s, 4 attempts)
INSERT INTO levels (id, name, description, difficulty, status, version, arrows, attempts, time_limit_seconds, created_at, updated_at)
VALUES (
  '550e8400-e29b-41d4-a716-446655440021',
  'Hard Timer',
  'Eight snakes against the clock.',
  'HARD',
  'PUBLISHED',
  1,
  '[{"id":"a","color":"blue","path":[{"row":0,"col":0},{"row":0,"col":1},{"row":0,"col":2},{"row":0,"col":3},{"row":0,"col":4},{"row":0,"col":5},{"row":0,"col":6}],"direction":"RIGHT"},{"id":"b","color":"green","path":[{"row":3,"col":1},{"row":3,"col":2},{"row":2,"col":2},{"row":1,"col":2}],"direction":"UP"},{"id":"c","color":"yellow","path":[{"row":5,"col":7},{"row":4,"col":7},{"row":3,"col":7},{"row":3,"col":8},{"row":3,"col":9}],"direction":"RIGHT"},{"id":"d","color":"pink","path":[{"row":2,"col":-1},{"row":2,"col":0},{"row":1,"col":0}],"direction":"UP"},{"id":"e","color":"cyan","path":[{"row":2,"col":6},{"row":1,"col":6},{"row":1,"col":7},{"row":1,"col":8}],"direction":"RIGHT"},{"id":"f","color":"purple","path":[{"row":3,"col":2},{"row":3,"col":3},{"row":3,"col":4},{"row":2,"col":4},{"row":1,"col":4}],"direction":"UP"},{"id":"g","color":"crimson","path":[{"row":4,"col":6},{"row":3,"col":6},{"row":3,"col":7}],"direction":"RIGHT"},{"id":"h","color":"white","path":[{"row":3,"col":1},{"row":3,"col":2},{"row":2,"col":2},{"row":1,"col":2}],"direction":"UP"}]'::jsonb,
  4,
  70,
  NOW(),
  NOW()
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  difficulty = EXCLUDED.difficulty,
  status = EXCLUDED.status,
  version = EXCLUDED.version,
  arrows = EXCLUDED.arrows,
  attempts = EXCLUDED.attempts,
  time_limit_seconds = EXCLUDED.time_limit_seconds,
  updated_at = EXCLUDED.updated_at;

-- Level 13: Hard Mesh (HARD, 8 arrows, 65s, 4 attempts)
INSERT INTO levels (id, name, description, difficulty, status, version, arrows, attempts, time_limit_seconds, created_at, updated_at)
VALUES (
  '550e8400-e29b-41d4-a716-446655440022',
  'Hard Mesh',
  'A mesh of eight long, bending bodies.',
  'HARD',
  'PUBLISHED',
  1,
  '[{"id":"a","color":"blue","path":[{"row":0,"col":0},{"row":0,"col":1},{"row":0,"col":2},{"row":0,"col":3},{"row":0,"col":4},{"row":0,"col":5},{"row":0,"col":6}],"direction":"RIGHT"},{"id":"b","color":"green","path":[{"row":3,"col":1},{"row":3,"col":2},{"row":2,"col":2},{"row":1,"col":2}],"direction":"UP"},{"id":"c","color":"yellow","path":[{"row":5,"col":7},{"row":4,"col":7},{"row":3,"col":7},{"row":3,"col":8},{"row":3,"col":9}],"direction":"RIGHT"},{"id":"d","color":"pink","path":[{"row":2,"col":-1},{"row":2,"col":0},{"row":1,"col":0}],"direction":"UP"},{"id":"e","color":"cyan","path":[{"row":2,"col":6},{"row":1,"col":6},{"row":1,"col":7},{"row":1,"col":8}],"direction":"RIGHT"},{"id":"f","color":"purple","path":[{"row":3,"col":2},{"row":3,"col":3},{"row":3,"col":4},{"row":2,"col":4},{"row":1,"col":4}],"direction":"UP"},{"id":"g","color":"crimson","path":[{"row":4,"col":6},{"row":3,"col":6},{"row":3,"col":7}],"direction":"RIGHT"},{"id":"h","color":"white","path":[{"row":3,"col":1},{"row":3,"col":2},{"row":2,"col":2},{"row":1,"col":2}],"direction":"UP"}]'::jsonb,
  4,
  65,
  NOW(),
  NOW()
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  difficulty = EXCLUDED.difficulty,
  status = EXCLUDED.status,
  version = EXCLUDED.version,
  arrows = EXCLUDED.arrows,
  attempts = EXCLUDED.attempts,
  time_limit_seconds = EXCLUDED.time_limit_seconds,
  updated_at = EXCLUDED.updated_at;

-- Level 14: Hard Snarl (HARD, 9 arrows, 60s, 4 attempts)
INSERT INTO levels (id, name, description, difficulty, status, version, arrows, attempts, time_limit_seconds, created_at, updated_at)
VALUES (
  '550e8400-e29b-41d4-a716-446655440023',
  'Hard Snarl',
  'Nine arrows snarled tight. Stay calm, read the order.',
  'HARD',
  'PUBLISHED',
  1,
  '[{"id":"a","color":"blue","path":[{"row":0,"col":0},{"row":0,"col":1},{"row":0,"col":2},{"row":0,"col":3},{"row":0,"col":4},{"row":0,"col":5},{"row":0,"col":6},{"row":0,"col":7}],"direction":"RIGHT"},{"id":"b","color":"green","path":[{"row":3,"col":1},{"row":3,"col":2},{"row":2,"col":2},{"row":1,"col":2}],"direction":"UP"},{"id":"c","color":"yellow","path":[{"row":5,"col":8},{"row":4,"col":8},{"row":3,"col":8},{"row":3,"col":9},{"row":3,"col":10}],"direction":"RIGHT"},{"id":"d","color":"pink","path":[{"row":2,"col":5},{"row":2,"col":6},{"row":1,"col":6}],"direction":"UP"},{"id":"e","color":"cyan","path":[{"row":2,"col":7},{"row":1,"col":7},{"row":1,"col":8},{"row":1,"col":9}],"direction":"RIGHT"},{"id":"f","color":"purple","path":[{"row":3,"col":1},{"row":3,"col":2},{"row":3,"col":3},{"row":2,"col":3},{"row":1,"col":3}],"direction":"UP"},{"id":"g","color":"crimson","path":[{"row":4,"col":7},{"row":3,"col":7},{"row":3,"col":8}],"direction":"RIGHT"},{"id":"h","color":"white","path":[{"row":3,"col":-1},{"row":3,"col":0},{"row":2,"col":0},{"row":1,"col":0}],"direction":"UP"},{"id":"i","color":"orange","path":[{"row":3,"col":8},{"row":2,"col":8},{"row":1,"col":8},{"row":1,"col":9},{"row":1,"col":10}],"direction":"RIGHT"}]'::jsonb,
  4,
  60,
  NOW(),
  NOW()
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  difficulty = EXCLUDED.difficulty,
  status = EXCLUDED.status,
  version = EXCLUDED.version,
  arrows = EXCLUDED.arrows,
  attempts = EXCLUDED.attempts,
  time_limit_seconds = EXCLUDED.time_limit_seconds,
  updated_at = EXCLUDED.updated_at;

-- Level 15: Hard Finale (HARD, 10 arrows, 55s, 3 attempts)
INSERT INTO levels (id, name, description, difficulty, status, version, arrows, attempts, time_limit_seconds, created_at, updated_at)
VALUES (
  '550e8400-e29b-41d4-a716-446655440024',
  'Hard Finale',
  'Ten snakes, three attempts, one clean solution.',
  'HARD',
  'PUBLISHED',
  1,
  '[{"id":"a","color":"blue","path":[{"row":0,"col":0},{"row":0,"col":1},{"row":0,"col":2},{"row":0,"col":3},{"row":0,"col":4},{"row":0,"col":5},{"row":0,"col":6},{"row":0,"col":7}],"direction":"RIGHT"},{"id":"b","color":"green","path":[{"row":3,"col":1},{"row":3,"col":2},{"row":2,"col":2},{"row":1,"col":2}],"direction":"UP"},{"id":"c","color":"yellow","path":[{"row":5,"col":8},{"row":4,"col":8},{"row":3,"col":8},{"row":3,"col":9},{"row":3,"col":10}],"direction":"RIGHT"},{"id":"d","color":"pink","path":[{"row":2,"col":5},{"row":2,"col":6},{"row":1,"col":6}],"direction":"UP"},{"id":"e","color":"cyan","path":[{"row":2,"col":7},{"row":1,"col":7},{"row":1,"col":8},{"row":1,"col":9}],"direction":"RIGHT"},{"id":"f","color":"purple","path":[{"row":3,"col":1},{"row":3,"col":2},{"row":3,"col":3},{"row":2,"col":3},{"row":1,"col":3}],"direction":"UP"},{"id":"g","color":"crimson","path":[{"row":4,"col":7},{"row":3,"col":7},{"row":3,"col":8}],"direction":"RIGHT"},{"id":"h","color":"white","path":[{"row":3,"col":-1},{"row":3,"col":0},{"row":2,"col":0},{"row":1,"col":0}],"direction":"UP"},{"id":"i","color":"orange","path":[{"row":3,"col":8},{"row":2,"col":8},{"row":1,"col":8},{"row":1,"col":9},{"row":1,"col":10}],"direction":"RIGHT"},{"id":"j","color":"teal","path":[{"row":2,"col":3},{"row":2,"col":4},{"row":1,"col":4}],"direction":"UP"}]'::jsonb,
  3,
  55,
  NOW(),
  NOW()
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  difficulty = EXCLUDED.difficulty,
  status = EXCLUDED.status,
  version = EXCLUDED.version,
  arrows = EXCLUDED.arrows,
  attempts = EXCLUDED.attempts,
  time_limit_seconds = EXCLUDED.time_limit_seconds,
  updated_at = EXCLUDED.updated_at;
