Feature: Leaderboard submit/read contract hardening

  The backend must own leaderboard identifiers and username snapshots while
  reporting scoreless known levels as empty leaderboards instead of errors.

  @s1
  Scenario: Authenticated submit stores server-owned ids and username
    Given an authenticated user exists with username "real_player"
    And a known level exists
    And the submit body contains only "levelId", "score", "timeSeconds", and "movesCount"
    When the client posts to "/leaderboard/scores"
    Then the API responds with status 201
    And the stored leaderboard id is generated by the server
    And the stored entry id is generated by the server
    And the stored username snapshot is "real_player"

  @s2
  Scenario: Spoofed submit identity fields are ignored
    Given an authenticated user exists with username "real_player"
    And a known level exists
    And the submit body also contains "leaderboardId", "entryId", "userId", and "usernameSnapshot"
    When the client posts to "/leaderboard/scores"
    Then the API responds with status 201
    And the stored leaderboard id does not come from the request body
    And the stored entry id does not come from the request body
    And the stored username snapshot is "real_player"

  @s3
  Scenario: Anonymous or invalid submit is rejected
    Given no valid bearer token is provided
    When the client posts to "/leaderboard/scores"
    Then the API responds with status 401
    And the response error code is "UNAUTHORIZED"

  @s4
  Scenario: Submit requires gameplay fields
    Given an authenticated user exists
    And the submit body is missing one of "levelId", "score", "timeSeconds", or "movesCount"
    When the client posts to "/leaderboard/scores"
    Then the API responds with status 400
    And the response error code is "BAD_REQUEST"

  @s5
  Scenario: Known scoreless level returns empty leaderboard
    Given a known level exists
    And no leaderboard row exists for that level
    When the client gets "/leaderboard/:levelId"
    Then the API responds with status 200
    And the response contains the level id
    And the response contains an empty entries list

  @s6
  Scenario: Unknown level still returns not found
    Given no level exists for the requested level id
    When the client gets "/leaderboard/:levelId"
    Then the API responds with status 404
    And the response error code is "NOT_FOUND"

  @s7
  Scenario: OpenAPI documents the slim submit contract
    Given the OpenAPI document is generated
    When the SubmitScoreRequest schema is inspected
    Then only "levelId", "score", "timeSeconds", and "movesCount" are required
    And "leaderboardId", "entryId", "userId", and "usernameSnapshot" are not documented as client-owned submit fields
